### ISSUE TITLE
Wrong filename in GWAS lesson

### ISSUE THREAD

**Issue by wltrimbl** [ngs-docs/angus#105]
The line defining `All_SKAT_Data_reduced` in `NGS_GWAS_via_SKAT.md` should be 

`All_SKAT_Data_reduced <- read.table(file = "data/SKAT_all_reduced-pvals.results", header =TRUE)`

**Comment by ctb** [comment]
Fixed in https://github.com/ttimbers/SKAT_NGS-2015/pull/4
