### ISSUE TITLE
Assembly lesson on readthedocs

### ISSUE THREAD

**Issue by lexnederbragt** [ngs-docs/angus#112]
Can the link on http://angus.readthedocs.org/en/2015/week3.html to the assembly material (now pointing to https://github.com/ngs-docs/angus/blob/2015/week3/LN_assembly.md) be made to point to http://angus.readthedocs.org/en/2015/week3/LN_assembly.html?

**Comment by ctb** [comment]
On Thu, Aug 27, 2015 at 10:20:05AM -0700, Lex Nederbragt wrote:

> Can the link on http://angus.readthedocs.org/en/2015/week3.html to the assembly material (now pointing to https://github.com/ngs-docs/angus/blob/2015/week3/LN_assembly.md) be made to point to http://angus.readthedocs.org/en/2015/week3/LN_assembly.html?

There is no LN_assembly.html - sphinx doesn't produce them from md.

**Comment by lexnederbragt** [comment]
The link works, though... http://angus.readthedocs.org/en/2015/week3/LN_assembly.html

Oh, formatting is suboptimal, got it.

```
Lex
```

**Comment by ctb** [comment]
does it?? Hmm.  It doesn't show up in my local build so this must be a
RTD thing.  I'll look into it.

**Comment by ctb** [comment]
figured it out!

**Comment by ctb** [comment]
https://docs.readthedocs.org/en/latest/getting_started.html?highlight=markdown#in-markdown

**Comment by lexnederbragt** [comment]
Good to know :-) Thanks.
