### ISSUE TITLE
running large scale blasts - what should we do?

### ISSUE THREAD

**Issue by ctb** [ngs-docs/angus#177]
https://angus.readthedocs.io/en/2017/running-blast-large-scale.html doesn't exist yet.

my thought was to run something that took a little while, output some data that we could use in https://angus.readthedocs.io/en/2017/visualizing-blast-scores-with-RStudio.html, and let us show off "starting something big and walking away for a bit."

my first naive thought was to calculate BLAST score distributions for some large reciprocal BLAST (e.g. ecoli vs shewanella or something), visualize it, and then ask students to pick a cutoff based on the graph, and maybe do a little bit of analysis of how many putative orthologs there are.

or we could drag [shmlast](https://github.com/camillescott/shmlast) into this.

@camillescott what do you think?

**Comment by camillescott** [comment]
Depends on what we think they'll be doing long-term. I'm not against introducing them to shmlast for RBH/CRBH, but they might be doing regular old searches more often. Do we want this lesson to focus more on the scale aspect, or on the downstream analysis?

**Comment by ctb** [comment]
for the purpose of visualization, it seems like a pairwise putative ortholog
search might work well.  or we could just do any ol' blast.

On Thu, Jun 22, 2017 at 06:34:19PM -0700, Camille Scott wrote:
> Depends on what we think they'll be doing long-term. I'm not against introducing them to shmlast for RBH/CRBH, but they might be doing regular old searches more often. Do we want this lesson to focus more on the scale aspect, or on the downstream analysis?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ngs-docs/angus/issues/177#issuecomment-310546488
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by camillescott** [comment]
If we wanna keep it simple, we can do shmlast for that -- it'll do regular old RBH just as well as CRBH.

**Comment by ctb** [comment]
ok - I will bang on this as I get a chance, either tonight or tomorrow.
any shmlast-speciifc links or resources I should pay attention to would be
very welcome!

**Comment by ctb** [comment]
aslo tag in #186
