### ISSUE TITLE
docker as a topic

### ISSUE THREAD

**Issue by ctb** [ngs-docs/angus#192]
we should at least mention this, and maybe demo it (if we have a group of people that are prepared for complexity in 2nd week)

**Comment by upendrak** [comment]
I agree. I would also add Singularity to it as well..

**Comment by ctb** [comment]
On Fri, Jun 23, 2017 at 08:45:42AM -0700, Upendra Kumar Devisetty wrote:
> I agree. I would also add Singularity to it as well..

yes! do you know of any singularity tutorials? I have some on docker
already.

**Comment by upendrak** [comment]
There aren't many tutorials available for Singularity but their website has a very nice tutorial - http://singularity.lbl.gov/singularity-tutorial.  XSEDE's stampede specific tutorial is also decent - https://github.com/TACC/TACC-Singularity. For Docker, do check this awesome tool - http://play-with-docker.com/
