### ISSUE TITLE
Rephrase username and password directions

### ISSUE THREAD

**Issue by NBKingsley** [ngs-docs/angus#198]
The file on booting a jetstream instance still talks about a username and password for the UCSC workshop. This should be changed to refer to ANGUS.

**Comment by ctb** [comment]
same username, but yes, should be changed to refering to ANGUS!

On Sat, Jun 24, 2017 at 08:28:07PM -0700, NBKingsley wrote:
> The file on booting a jetstream instance still talks about a username and password for the UCSC workshop. This should be changed to refer to ANGUS.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ngs-docs/angus/issues/198
-- 
C. Titus Brown, ctbrown@ucdavis.edu
