### ISSUE TITLE
variant calling lesson probz: EOF error, installs, etc

### ISSUE THREAD

**Issue by jessicalumian** [ngs-docs/angus#224]
Problems I see from variant calling lesson:
(https://github.com/ngs-docs/angus/blob/2017/variant-calling.md)

- EOF error on command to sort bam file by position in genome `samtools sort SRR2584857.bam SRR2584857.sorted`
- no installation for vcftools
- extracting reads command at the end of lesson has same position in e. coli genome `samtools view SRR2584857.sorted.bam 'ecoli:920514-920514' > out.bam`
- also for previous line, should be out.sam to be human readable and compatible with `wc -l`

I'll try and fix some of these tomorrow!

**Comment by tseemann** [comment]
The samtools EOF error is not a real error. It was fixed in later versions of samtools.

The best practice is to skip the SAM step, with samtools 1.x you can do `bwa -t 6 ref reads | samtools sort > reads.bam` directly!
