### ISSUE TITLE
md5sum

### ISSUE THREAD

**Issue by aihudson** [ngs-docs/angus#379]
Running the md5sum ended up being confusing for Bears because they didn't understand why you would do it. In our room we ended up actually generating an md5sum text file and running md5sum -c to demo how you'd use it in real life. I think it might be good to have the students download an md5sum text file and do md5sum -c in the lesson to show the actual process as it might make more sense that way. Plus, knowing how to check md5sums and why you do that is important and can be confusing (or at least it was to me when I learned it).

**Comment by johnsolk** [comment]
Tristan ran:
```
md5sum *.fastq.gz > err_md5sum.txt
```

Then:
```
md5sum -c err_md5sum.txt
```
This might be a good addition to the lesson. I think it is super useful!
