### ISSUE TITLE
update CoC

### ISSUE THREAD

**Issue by raynamharris** [ngs-docs/angus#414]
The CoC page is a little out of date. https://angus.readthedocs.io/en/2019/code-of-conduct.html

The current version can be viewed at http://ivory.idyll.org/dibsi/coc.html or https://github.com/dib-lab/dibsi/blob/master/coc.md

**Comment by ctb** [comment]
the much updated CoC is at http://ivory.idyll.org/dibsi/coc.html, but good
catch - we'll move it over to angus or provide a pointer!

thx,
--titus

On Fri, Jun 28, 2019 at 11:21:54AM -0700, Rayna M Harris wrote:
> The CoC page is a little out of date. https://angus.readthedocs.io/en/2019/code-of-conduct.html
> 
> The current version can be viewed at http://ivory.idyll.org/dibsi/coc.html or https://github.com/dib-lab/dibsi/blob/master/coc.md
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ngs-docs/angus/issues/414
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ctb** [comment]
Updated in https://github.com/ngs-docs/angus/pull/419.
