### ISSUE TITLE
md5sum error

### ISSUE THREAD

**Issue by katffowler** [ngs-docs/angus#429]
@taylorreiter in the following code in the quality and trimming module...

To check whether your md5sum hashes match with a file containing md5sum hashes:

md5sum *.fastq.gz > md5sum.txt
md5sum -c err_md5sum.txt

...the .txt files are named differently, and running the second command returns a "file not found" error. Changing the name in the second command to match the first fixed the issue.

**Comment by taylorreiter** [comment]
addressed! good catch @katffowler
