### ISSUE TITLE
trial run of new deseq2 material

### ISSUE THREAD

**Issue by taylorreiter** [ngs-docs/angus#438]
@katffowler there is a draft of the new DESeq2 differential expression and visualization material [here](https://github.com/ngs-docs/angus/blob/2019/diff-ex-and-viz.md). If you would be willing to test it out from the IP address I gave you before, that would be very helpful!

**Comment by katffowler** [comment]
hey @taylorreiter , found 2 problems. the first (might be specific to my instance?) is that I can't use ```head()```. Returns the error "package not found : fansi" despite head being present in the package "utils", which installed.

The second is that there is no colname or object quant_files, but it is called in the following line:

```txi <- tximport(files = samples$quant_file, type = "salmon", tx2gene = tx2gene_map)```

Tried to mess around with it but I couldn't figure out a fix.

**Comment by taylorreiter** [comment]
great, thank you @katffowler! I think the first one we can tell the other instructors that it's a known problem that could occur, that should be able to be fixed with `base::head()`

I'll fix the second one now!

**Comment by katffowler** [comment]
```base::head()``` didn't work in the instance we're using,but I tried using head in another available instance that the learners have access to and it worked, so I think that'll be fine
