### ISSUE TITLE
add a license to the repo?

### ISSUE THREAD

**Issue by taylorreiter** [ngs-docs/angus#533]
I'd like to re-use some of the lessons I wrote for some new lessons I'll be teaching soon, and I noticed the repo doesn't have a license. Would it be possible to add one, maybe similar to the one used in the data carpentry genomics lesson? https://datacarpentry.org/genomics-workshop/LICENSE.html
https://github.com/datacarpentry/genomics-workshop/blob/gh-pages/LICENSE.md

**Comment by ctb** [comment]
hmm, this should all be under CC0, and there is an old template that has that listed, but it's not on this repo yet either. I will look into it.

**Comment by ctb** [comment]
(but yes)

**Comment by ctb** [comment]
I believe the lessons have a CC0 on the bottom.

**Comment by ctb** [comment]
fixing in #536, which adds license to each page footer.
