### ISSUE TITLE
angus 2019 doc pages not rendering correctly

### ISSUE THREAD

**Issue by AstrobioMike** [ngs-docs/angus#535]
Heya! 

Random, but just came across this. 

The angus 2019 doc pages aren't rendering properly. E.g., the index here: https://angus.readthedocs.io/en/2019/ ; and another page here: https://angus.readthedocs.io/en/2019/quality-and-trimming.html

2018 and earlier seem to work fine. I'm not spotting any difference between the 2018 and 2019 branches that might be causing the problem, but i'm also not really familiar with readthedocs ¯\_(ツ)_/¯ Maybe someone else will spot it right away

**Comment by ctb** [comment]
Fixing in #536 - tl;dr switching over to myst_parser instead of recommonmark fixed the problem.
