### ISSUE TITLE
Comments on Introduction to Docker

### ISSUE THREAD

**Issue by achabotl** [ngs-docs/angus#96]
Comment about the [Intro to Docker tutorial](https://github.com/ngs-docs/angus/blob/2015/week3/CTB_docker.rst).
- If the students are already familiar with Git, then it might make sense to make some parallel between container ID's and git commits, and container "name" and git tags. Docker is essentially building a tree based on the base container.
- When building the Dockerfile, it would be better to put the `apt-get update` and `apt-get install` on the same line, the same way it was done interactively. It has a few benefits: it builds only one layer, and the install runs only if the update is successful. Arguably, the git clone and the `make` call could be together too, but that might obscure things too much. It's probably better to just stick to the sequence of actions done interactively, i.e. the dockerfile is essentially the content of `history` with a few special commands prepended to each line.

**Comment by ctb** [comment]
Thanks!

Connecting concepts to git would work for some but not all.

Re apt-get, thanks, will do next time I update the tutorial!
